services:
  php-fpm:
    build:
      context: ./php-fpm
      target: production
    volumes:
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
    environment:
      - PHP_DATE_TIMEZONE=${PHP_DATE_TIMEZONE}
      - PHP_DISPLAY_ERRORS=${PHP_DISPLAY_ERRORS}
      - PHP_DISPLAY_STARTUP_ERRORS=${PHP_DISPLAY_STARTUP_ERRORS}
      - PHP_ERROR_LOG=${PHP_ERROR_LOG}
      - PHP_ERROR_REPORTING=${PHP_ERROR_REPORTING}
      - PHP_FPM_PM_CONTROL=${PHP_FPM_PM_CONTROL}
      - PHP_FPM_PM_MAX_CHILDREN=${PHP_FPM_PM_MAX_CHILDREN}
      - PHP_FPM_PM_MAX_SPARE_SERVERS=${PHP_FPM_PM_MAX_SPARE_SERVERS}
      - PHP_FPM_PM_MIN_SPARE_SERVERS=${PHP_FPM_PM_MIN_SPARE_SERVERS}
      - PHP_FPM_PM_START_SERVERS=${PHP_FPM_PM_START_SERVERS}
      - PHP_FPM_POOL_NAME=${PHP_FPM_POOL_NAME}
      - PHP_FPM_PROCESS_CONTROL_TIMEOUT=${PHP_FPM_PROCESS_CONTROL_TIMEOUT}
      - PHP_MAX_EXECUTION_TIME=${PHP_MAX_EXECUTION_TIME}
      - PHP_MAX_INPUT_TIME=${PHP_MAX_INPUT_TIME}
      - PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT}
      - PHP_OPCACHE_ENABLE=${PHP_OPCACHE_ENABLE}
      - PHP_OPCACHE_INTERNED_STRINGS_BUFFER=${PHP_OPCACHE_INTERNED_STRINGS_BUFFER}
      - PHP_OPCACHE_MAX_ACCELERATED_FILES=${PHP_OPCACHE_MAX_ACCELERATED_FILES}
      - PHP_OPCACHE_MEMORY_CONSUMPTION=${PHP_OPCACHE_MEMORY_CONSUMPTION}
      - PHP_OPCACHE_REVALIDATE_FREQ=${PHP_OPCACHE_REVALIDATE_FREQ}
      - PHP_OPEN_BASEDIR=${PHP_OPEN_BASEDIR}
      - PHP_POST_MAX_SIZE=${PHP_POST_MAX_SIZE}
      - PHP_SESSION_COOKIE_SECURE=${PHP_SESSION_COOKIE_SECURE}
      - PHP_UPLOAD_MAX_FILE_SIZE=${PHP_UPLOAD_MAX_FILE_SIZE}
    restart: always
    privileged: true

  caddy:
    build:
      context: ./caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./appdata/caddy/logs:/var/log/caddy
      - ./appdata/caddy/.caddy:/root/.caddy
      - ./appdata/caddy/data:/data
    restart: always
